; Generated by agamc — Agam Compiler
@agam_argc_storage = internal local_unnamed_addr global i32 0
@agam_argv_storage = internal local_unnamed_addr global i8** null
declare noundef i32 @printf(i8* nocapture noundef readonly, ...) local_unnamed_addr #0
declare noundef i64 @strtoll(i8* nocapture noundef readonly, i8** nocapture, i32 noundef) local_unnamed_addr #1

@.str.0 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"

define noundef i32 @agam_argc() local_unnamed_addr #2 {
entry:
%0 = load i32, i32* @agam_argc_storage
ret i32 %0
}

define noundef i8* @agam_argv(i32 noundef %index) local_unnamed_addr #3 {
entry:
%0 = load i8**, i8*** @agam_argv_storage
%1 = sext i32 %index to i64
%2 = getelementptr inbounds i8*, i8** %0, i64 %1
%3 = load i8*, i8** %2
ret i8* %3
}

define noundef i32 @agam_parse_int(i8* nocapture noundef readonly %s) local_unnamed_addr #1 {
entry:
%0 = call i64 @strtoll(i8* noundef %s, i8** null, i32 noundef 10)
%1 = trunc i64 %0 to i32
ret i32 %1
}

define noundef i32 @main(i32 noundef %argc, i8** noundef %argv) local_unnamed_addr norecurse {
block_0:
  store i32 %argc, i32* @agam_argc_storage
  store i8** %argv, i8*** @agam_argv_storage
  %tmp0 = sext i32 42 to i64
  %tmp1 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @.str.0, i64 0, i64 0), i64 %tmp0)
  ret i32 0
}

attributes #0 = { nofree nounwind }
attributes #1 = { nofree nounwind willreturn }
attributes #2 = { nofree norecurse nosync nounwind willreturn }
attributes #3 = { nofree norecurse nosync nounwind willreturn }
